CREATE TABLE APP_USER
(
    ID                      bigint generated by default as identity,
    FIREBASE_EMAIL          varchar(255),
    FIREBASE_EMAIL_VERIFIED boolean,
    FIREBASE_ISSUER         varchar(255),
    FIREBASE_NAME           varchar(255),
    FIREBASE_PICTURE        varchar(255),
    FIREBASE_UID            varchar(255),
    PHONE_NUMBER            varchar(255),
    primary key (ID)
);
CREATE TABLE OFFER
(
    ID                     bigint generated by default as identity,
    BACKGROUND_DESCRIPTION varchar(255),
    FIRST_NAME             varchar(255),
    LAST_NAME              varchar(255),
    LONG_DESCRIPTION       varchar(255),
    RATE_DESCRIPTION       varchar(255),
    SHORT_DESCRIPTION      varchar(255),
    UUID                   uuid NOT NULL,
    APP_USER_ID            bigint,
    primary key (ID),
    foreign key (APP_USER_ID) references APP_USER (ID)
);
CREATE TABLE PRICE
(
    ID          bigint generated by default as identity,
    DESCRIPTION varchar(255),
    PRICE       numeric,
    CURRENCY    varchar(255),
    MAIN_PRICE  boolean,
    OFFER_ID    bigint,
    primary key (ID),
    foreign key (OFFER_ID) references OFFER (ID)

);
CREATE TABLE OPINION
(
    ID          bigint generated by default as identity,
    TITLE       varchar(255),
    CONTENT     varchar(255),
    RATE        int,
    OFFER_ID    bigint,
    CREATED_AT  timestamp,
    APP_USER_ID bigint,
    primary key (ID),
    foreign key (OFFER_ID) references OFFER (ID),
    foreign key (APP_USER_ID) references APP_USER (ID)
);
CREATE TABLE EXPERIENCE
(
    ID   bigint generated by default as identity,
    NAME varchar(255),
    OFFER_ID bigint,
    primary key (ID),
    foreign key (OFFER_ID) references OFFER(ID)
);
CREATE TABLE SKILL
(
    ID    bigint generated by default as identity,
    VALUE varchar(255),
    EXPERIENCE_ID bigint,
    primary key (ID),
    foreign key (EXPERIENCE_ID) references EXPERIENCE(ID)
);