CREATE TABLE APP_USER (
                          ID bigint generated by default as identity,
                          FIREBASE_EMAIL varchar(255),
                          FIREBASE_EMAIL_VERIFIED boolean,
                          FIREBASE_ISSUER varchar(255),
                          FIREBASE_NAME varchar(255),
                          FIREBASE_PICTURE varchar(255),
                          FIREBASE_UID varchar(255),
                          primary key (ID)
);
CREATE TABLE OFFER (
                       ID bigint generated by default as identity,
                       BACKGROUND_DESCRIPTION varchar(255),
                       FIRST_NAME varchar(255),
                       LAST_NAME varchar(255),
                       LONG_DESCRIPTION varchar(255),
                       PRICE decimal(19,2),
                       RATE_DESCRIPTION varchar(255),
                       SHORT_DESCRIPTION varchar(255),
                       UUID uuid NOT NULL,
                       APP_USER_ID bigint,
                       primary key (ID),
                       foreign key (APP_USER_ID) references APP_USER(ID)
);