CREATE TABLE APP_USER
(
    ID                      bigint generated by default as identity,
    FIREBASE_EMAIL          varchar(255),
    FIREBASE_EMAIL_VERIFIED boolean,
    FIREBASE_ISSUER         varchar(255),
    FIREBASE_NAME           varchar(255),
    FIREBASE_PICTURE        varchar(255),
    FIREBASE_UID            varchar(255),
    PHONE_NUMBER            varchar(255),
    primary key (ID)
);
CREATE TABLE OFFER
(
    ID                     bigint generated by default as identity,
    BACKGROUND_DESCRIPTION varchar(255),
    FIRST_NAME             varchar(255),
    LAST_NAME              varchar(255),
    LONG_DESCRIPTION       varchar(255),
    RATE_DESCRIPTION       varchar(255),
    SHORT_DESCRIPTION      varchar(255),
    UUID                   uuid NOT NULL,
    APP_USER_ID            bigint,
    primary key (ID),
    foreign key (APP_USER_ID) references APP_USER (ID)
);
CREATE TABLE PRICE
(
    ID          bigint generated by default as identity,
    DESCRIPTION varchar(255),
    PRICE       numeric,
    CURRENCY    varchar(255),
    MAIN_PRICE  boolean,
    OFFER_ID    bigint,
    primary key (ID),
    foreign key (OFFER_ID) references OFFER (ID)

);
CREATE TABLE OPINION
(
    ID          bigint generated by default as identity,
    TITLE       varchar(255),
    CONTENT     varchar(255),
    RATE        int,
    OFFER_ID    bigint,
    CREATED_AT  timestamp,
    APP_USER_ID bigint,
    primary key (ID),
    foreign key (OFFER_ID) references OFFER (ID),
    foreign key (APP_USER_ID) references APP_USER (ID)
);
CREATE TABLE EXPERIENCE
(
    ID   bigint generated by default as identity,
    NAME varchar(255),
    OFFER_ID bigint,
    primary key (ID),
    foreign key (OFFER_ID) references OFFER(ID)
);
CREATE TABLE SKILL
(
    ID    bigint generated by default as identity,
    VALUE varchar(255),
    EXPERIENCE_ID bigint,
    primary key (ID),
    foreign key (EXPERIENCE_ID) references EXPERIENCE(ID)
);
CREATE TABLE SPECIALIZATION
(
    ID   bigint generated by default as identity,
    SHORT_NAME varchar(255),
    LONG_NAME varchar(255),
    ICON_IMAGE varchar(255),
    VERIFIED boolean,
    primary key (ID)
);

CREATE TABLE OFFER_SPECIALIZATIONS
(
    OFFER_ID bigint not null,
    SPECIALIZATION_ID bigint not null,
    primary key (OFFER_ID,SPECIALIZATION_ID),
    foreign key (OFFER_ID) references OFFER(ID),
    foreign key (SPECIALIZATION_ID) references SPECIALIZATION(ID)
);

CREATE TABLE ROLE
(
      ROLE_ID   bigint generated by default as identity,
      NAME varchar(45) NOT NULL,
      PRIMARY KEY (ROLE_ID)
);

CREATE TABLE USER_ROLE (
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    primary key (USER_ID,ROLE_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES APP_USER (ID)
);