import { Grid, Paper, Typography } from "@mui/material";
import { HomepageStyles as styles } from "./homepage-styles";
import { HOMEPAGE_OFFERSTILES_TITLE } from "../../utility/constants";

export const HomepageOffersTiles = () => {
  //TODO: remove fakeData and pass data form OfferService when there will be enough records in offers
  const fakeData = [
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Python",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Java",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Java",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "MySQL",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Python",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Django",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Spring",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "C#",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "React",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Ruby",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Perl",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Javascript",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Golang",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Typescript",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Visual Basic",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Java",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "PHP",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Ruby",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "PHP",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Python",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Perl",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
    {
      backgroundDescription: "Java",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "string",
    },
  ];

  return (
    <Grid container>
      <Grid item xs={12}>
        <Typography variant="h3" sx={styles.offerTilesTitle}>
          {HOMEPAGE_OFFERSTILES_TITLE}
        </Typography>
      </Grid>
      <Grid container xs={12} spacing={2} sx={styles.offerTilesContainer}>
        {fakeData.slice(0, 18).map((item) => (
          <Grid item lg={2} md={4} sm={6} xs={6}>
            <Paper sx={styles.offerGridItem}>
               {item.backgroundDescription}
            </Paper>
          </Grid>
        ))}
      </Grid>
    </Grid>
  );
};
