import { Grid, Paper, Typography } from "@mui/material";
import { HomepageStyles as styles } from "./homepage-styles";
import { HOMEPAGE } from "../../utility/constants";

export const HomepageOffersTiles = () => {
  //TODO: remove fakeData and pass data form OfferService when there will be enough records in offers
  const fakeData = [
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "1",
    },
    {
      backgroundDescription: "Python",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "2",
    },
    {
      backgroundDescription: "Java",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "3",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "4",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "5",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "6",
    },
    {
      backgroundDescription: "Java",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "7",
    },
    {
      backgroundDescription: "MySQL",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "8",
    },
    {
      backgroundDescription: "Python",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "9",
    },
    {
      backgroundDescription: "Django",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "10",
    },
    {
      backgroundDescription: "Spring",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "11",
    },
    {
      backgroundDescription: "C#",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "12",
    },
    {
      backgroundDescription: "React",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "13",
    },
    {
      backgroundDescription: "Ruby",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "14",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "15",
    },
    {
      backgroundDescription: "Perl",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "16",
    },
    {
      backgroundDescription: "Javascript",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "17",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "18",
    },
    {
      backgroundDescription: "Golang",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "19",
    },
    {
      backgroundDescription: "Typescript",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "20",
    },
    {
      backgroundDescription: "Visual Basic",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "21",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "22",
    },
    {
      backgroundDescription: "Java",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "23",
    },
    {
      backgroundDescription: "PHP",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "24",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "25",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "26",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "27",
    },
    {
      backgroundDescription: "Ruby",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "28",
    },
    {
      backgroundDescription: "PHP",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "29",
    },
    {
      backgroundDescription: "C++",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "30",
    },
    {
      backgroundDescription: "Python",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "31",
    },
    {
      backgroundDescription: "Perl",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "32",
    },
    {
      backgroundDescription: "Java",
      firstName: "string",
      lastName: "string",
      longDescription: "string",
      price: 0,
      rateDescription: "string",
      shortDescription: "string",
      uuid: "33",
    },
  ];

  return (
    <>
      <Grid container sx={styles.mainContainer}>
        <Grid item xs={11} lg={8}>
        <Typography variant="h3" sx={styles.offerTilesTitle}>
          {HOMEPAGE.OFFERSTILES_TITLE}
        </Typography>
      </Grid>
      <Grid container columns={12} spacing={2} sx={styles.offerTilesContainer}>
        {fakeData.slice(0, 18).map((item) => (
          <Grid item lg={2} md={4} sm={6} xs={6} key={item.uuid}>
            <Paper sx={styles.offerGridItem}>
               {item.backgroundDescription}
            </Paper>
          </Grid>
        ))}
        </Grid>
      </Grid>
      </>
  );
};
