export const appTopBarConf = {
    boxPaddingTop: '25px',
    appBarMaxWidth: '1650px',
    menuPaperHeight: '354px',
    menuPaperWidth: '342px',
    menuPaperBorderRadius: '40px',
    menuPaperBackdropBlurFilter: '40px',
    menuRoundedIconFontSize: 60,
    menuItemFontSize: 24,
    menuItemPaddingTop: '20px',
    menuItemPaddingBottom: '20px',
    menuItemHoverColor: '#04ADBF',
    iconButtonMarginLeft: '260px',
    menuItemPadding: '10px',
    highlightOffOutlinedIconFontSize: 50 
}

export const searchInputConf = {
    paperWidth: '454px',
    paperHeight: '76px',
    paperBorderRadius: '38px',
    paperZIndex: 1,
    listBoxPropsHeight: '250px',
    autocompletePaperWidth: '362px',
    autocompletePaperHeight: '298px',
    autocompletePaperBorderRadius: '40px',
    autocompletePaperMarginTop: '5px',
    autocompletePaperPadding: '20px',
    autocompletePaperMarginLeft: '-42px',
    iconButtonWidth: '92px',
    iconButtonBackgroundColor: 'primary.main',
    iconButtonBorderRadius: '38px',
    iconButtonzIndex: 3,
    iconButtonHoverBackgroundColor: 'secondary.main',
    searchIconFontSize: 46,
    searchIconColor: 'white',
    autocompleteInputWidth: '70%',
    autocompletePaddingleft: '42px',
}

export const homepageConf = {
    homepageHeroSearchGridItemPaddingTopLG: '200px',
    inputContainerWidth: '100%',
    heroHeaderPaddingBottom: '20px',
    heroSubheaderPaddingTop: '20px',
    stepsSectionContainerMargin: '100px',
    stepsGridItemWidth: '100%',
    stepsGridItemHeight: '300px',
    stepsGridItemImgMarginBottom: '20px',
    stepsGridItemH5MarginTop: '10px',
    stepsGridItemH5MarginBottom: '30px',
    hideOnMobileStepsGridItemWidth: '100%',
    hideOnMobileStepsGridItemHeight: '300px',
    hideOnMobileStepsGridItemImgMarginBottom: '20px',
}